- name: "Installing additional software"
  yum: pkg={{ item }} state=installed
  with_items:
        - bind-utils
        - git
        - vim
        - ntp
        - at
        - lvm2
        - zsh
        - wget
        - gcc
        - java
        - links
        - httpd

- name: "upgrade all packages"
  yum:
    name: '*'
    state: latest

- name: "install the 'Development tools' package group"
  yum:
    name: "@Development tools"
    state: present

- name: "installing epel-release"
  yum:
    name: "epel-release"
    state: latest

- name: "installing node.js"
  yum:
    name: "nodejs"
    state: latest

- name: "node version"
  shell: 'node --version'

- name: "installing npm"
  yum:
    name: "npm"
    state: latest

